### ISSUE TITLE
Icon does not work with EmberJS 3.10

### ISSUE THREAD

**Issue by BryanHunt** [ember-elements/ember-elements#120]
**Describe the bug**
I'm trying to update my app to EmberJS 3.10 and the first problem I ran into is Icon not working.
I get the following error:

```
Uncaught Error: icon name is not valid
```

**To Reproduce**
```html
<Icon @icon="calendar"></Icon>
```

**Comment by jugaadi** [comment]
Closing this issue in favor of #123
