### ISSUE TITLE
Popover doesn't play nice with async content

### ISSUE THREAD

**Issue by BryanHunt** [ember-elements/ember-elements#62]
**Describe the bug**
If you use ember-promise-helpers to render async properties inside a Popover, the content is not rendered properly.  Example:

```
<PopOver class="approval-popover" @minimal={{true}} @icon={{this.resultIcon}} @isOutClickClose={{true}} @placement="auto" @canEscapeKeyClose={{true}}>
  <div class="approval-summary">
    {{await approvalSummary}}
  </div>
</PopOver>
```

**Comment by LowBP** [comment]
@BryanHunt  I am not able to trace out what u are doing. But based on `ember-promise-helpers` It is working when i do with a simple [test case](https://github.com/fivetanley/ember-promise-helpers/blob/master/tests/integration/await-test.js#L57) 
in `component.js`
```
  store: Ember.inject.service(),
    testEPromise: computed('simple', function () {
        let deferred1 = RSVP.defer();
        this.set('deferred1', deferred1);
        this.set('promise', deferred1.promise);
        return this.promise;
    }),
    actions: {
        onClick() {
            const deferred1Text = 'hi';
            this.deferred1.resolve(deferred1Text);
            this.set('promise', this.deferred1.promise);
        }
    }
```
in `templated.hbs`
```
<button {{action "onClick"}}>
  resolvePromise
</button>
<PopOver @btnTitle="Open popover" @intent="primary" @icon="code">
  <div>
    <h5 class="bp3-heading">
      Resolve Promise
    </h5>
    <p>
      {{testEPromise}}
      {{await testEPromise}}
    </p>
  </div>
</PopOver>
```

**Comment by BryanHunt** [comment]
I noticed tonight that the popover render problem only occurs the first time it is rendered (when we are waiting on the promise to fulfill).  Here is what I see:

<img width="284" alt="popover" src="https://user-images.githubusercontent.com/504299/56937865-90623400-6ac4-11e9-8617-0cc520d04fed.png">

Maybe the problem is related to trying to render the popover near the edge of the window?

Here is the second render:

<img width="468" alt="popover" src="https://user-images.githubusercontent.com/504299/56937902-c4d5f000-6ac4-11e9-89f6-b1633c988e68.png">

Note that the top of the popover getting cut off is probably #75
