### ISSUE TITLE
Button onClick causes ember proxy socket hangup

### ISSUE THREAD

**Issue by BryanHunt** [ember-elements/ember-elements#78]
**Describe the bug**
I have a login form that I'm using with ember-simple-auth and ember-simple-auth-token.  When I click the login button, ember-simple-auth-token sends a POST to the server to validate the user's credentials and the EmberJS proxy is crashing because of:

```
Error: socket hang up
    at createHangUpError (_http_client.js:335:17)
    at Socket.socketCloseListener (_http_client.js:376:25)
    at Socket.emit (events.js:201:15)
    at TCP.<anonymous> (net.js:586:12)
```

I think the underlying problem is related to ember-elements because I added a basic html button and  when I click the basic button, the POST works.  I also tried running without the Ember proxy and it still crashes - you just don't get the stack trace like you do when running with the proxy.

**To Reproduce**
1. Create a login form that uses ember-simple-auth and ember-simple-auth-token
```js
<form class="login-form">
  <FormGroup @label="User Name">
    <InputGroup @placeholder="" @value={{this.userId}} @onChange={{action (mut this.userId)}}/>
  </FormGroup>

  <FormGroup @label="Password">
    <InputGroup @placeholder="" @type="password" @value={{this.password}} @onChange={{action (mut this.password)}}/>
  </FormGroup>

  <div class="login-button">
    {{!-- Using this button fails --}}
    <Button @intent="primary" @onClick={{action "login"}}>Login</Button>
    {{!-- Using this button works --}}
    <button {{action "login"}}>Login</button>
  </div>
</form>
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 73.0.3683.103

**Comment by BryanHunt** [comment]
Here is a bit more info ... I enabled breakpoints on caught exceptions in the debugger and it triggers in ember-fetch when using the elements button, but not when using the plain html button.  Here is where it triggers:

<img width="1446" alt="Dummy 2019-05-01 09-40-42" src="https://user-images.githubusercontent.com/504299/57022594-3ad97480-6bf5-11e9-872b-498f284de330.png">

**Comment by LowBP** [comment]
@BryanHunt what is the version of `ember-cli` and `npm`?

**Comment by BryanHunt** [comment]
I'm using ember-cli 3.9.0 and yarn 1.15.2.

**Comment by LowBP** [comment]
@BryanHunt I have tested  `ember-simple-auth` and `ember-simple-auth-token` in [new ember app](https://github.com/pranavliag/test-EE) with help of ember `http-mock` server . There is no problem with `Button` component. Please [join our Slack group to talk to us](https://dunkinbase.slack.com/messages)

**Comment by BryanHunt** [comment]
I think I need an invite to the slack group.

**Comment by jugaadi** [comment]
@BryanHunt  [Please join our Slack group here](https://join.slack.com/t/dunkinbase/shared_invite/enQtNTkzOTg1MzAwOTQ1LWVkNTc0YTQ3ZWJlNDZhNDNlNmU5MjMzNDczNjFkZWZjNTVkNmI5MGU0ZmMyZGY5ZmRhNmZiYmFiMmM0YTY4ZGI).

**Comment by BryanHunt** [comment]
Try this: https://github.com/BryanHunt/test-login

```
yarn install
ember s
```

If you click the plain html button, you should get a 404.  If you click the elements button, the page should reload.

**Comment by BryanHunt** [comment]
For anyone else landing here ...

It turns out that doing:

```html
<form>
  <Button @onClick={{action "login"}}>Login</Button>
</form>
```
is very bad.  The better way (and working way) is:
```html
<form {{action="login" on="submit"}}>
  <Button @type="submit">Login</Button>
</form>
```
