### ISSUE TITLE
Problems with CheckBox

### ISSUE THREAD

**Issue by BryanHunt** [ember-elements/ember-elements#92]
**Describe the bug**
I'm having two issues with CheckBox.
1. The checked icon doesn't appear when the checkbox is checked.
2. The checkbox has an outline around it - I see it's coming from your accessibility CSS but I'd like to turn it off - that's how your documentation example works.

**To Reproduce**
```html
<CheckBox>Test</CheckBox>
```

**Screenshots**
<img width="205" alt="NvK8sUi 2019-05-08 14-10-17" src="https://user-images.githubusercontent.com/504299/57401334-0b011280-719b-11e9-9789-615ccec69ba6.png">

**Comment by LowBP** [comment]
@BryanHunt Please add [<Accessibility @isFocusOnTabs={{true}} />](https://github.com/dunkinbase/ember-elements/edit/master/tests/dummy/app/templates/application.md)   to your main `template.hbs` and I will update it in next version.
